#! ---------------------------------------------------------------
#! Aurora Theme for Hexo
#! ---------------------------------------------------------------
#! Designed & Coded By TriDiamond
#! ---------------------------------------------------------------

#! ---------------------------------------------------------------
#! Site Configs
#！ @docs https://aurora.tridiamond.tech/guide/configuration.html
#! ---------------------------------------------------------------
site:
  # 博客子标题，页面主标题后面会跟随这个标题内容。
  subtitle: Cxzxy's Blog
  author: Cxzxy
  # 博客子名字，会在 header 的 logo 下方显示
  nick: Cxzxy
  description:
  link: '/'
  language: cn
  # 开启博客的多语言支持
  multi_language: true
  # Logo 的图片链接 image
  logo: https://img-blog.csdnimg.cn/20210313122054101.png
  # 头像的图片链接 image
  avatar: https://img-blog.csdnimg.cn/20210313122054101.png
  # 备案信息
  beian:
    number: ''
    link: ''
  police_beian:
    number: ''
    link: ''

#! ---------------------------------------------------------------
#! Authors Configs
#！ @docs https://aurora.tridiamond.tech/guide/authors.html
#! ---------------------------------------------------------------
authors:
  ##! example
  # TriDiamond:
  #   name: TriDiamond
  #   avatar: https://up.enterdesk.com/edpic_source/44/ff/3d/44ff3d6bd2819d524facfcc33205d4cd.jpg
  #   link: https://github.com/TriDiamond
  #   description: 'Think like an artist, code like an artisan.'
  #   socials:
  #     github: https://tridiamond.tech

#! ---------------------------------------------------------------
#! Menu Configs
#！ @docs https://aurora.tridiamond.tech/guide/menu.html
#! ---------------------------------------------------------------
menu:
  # About: true
  Tags: true

  Archives: true
  # 自定义菜单, 外部链接
  special-column:
    name: '专栏'
    children:
      knowledge:
        name: '知识'
        path: '/page/knowledge'
      life:
        name: '生活'
        path: '/page/life'
  # 多级 projects 菜单配置
  projects:
    name: '链接'
    children:
      Fan:
        name: '阳'
        path: 'https://github.com/cxzxy/cxzxy.github.io.git'
      Email:
        name: '邮件'
        path: 'mailto:fanj.zh@foxmail'

theme:
  # 深色模式 true、false、auto
  dark_mode: true
  # 头像形状
  profile_shape: diamond # support `circle`, `diamond`, `rounded`
  # 推荐文章
  feature: true
  # 渐变颜色
  gradient:
    color_1: '#24c6dc'
    color_2: '#5433ff'
    color_3: '#ff0099'

# 社交链接
socials:
  github: 'https://github.com/Fan223'
  twitter: ''
  stackoverflow: ''
  weibo: 'https://weibo.com/u/7318914058'
  zhihu: 'https://www.zhihu.com/people/tridiamond'
  csdn: 'https://blog.csdn.net/ACE_U_005A'
  juejin: 'https://juejin.cn/user/1873223546578589'
  # 自定义社交连接
  customs:
  ##! Example:
  ##! --- Using SVG
  bilibili:
    icon: http://localhost:4000/svg/bilibili.svg
    link: https://live.bilibili.com/22619211

  ##! --- Using IconFont
  baidu:
    icon: iconfont icon-baidu
    link: https://live.bilibili.com/22619211

  ##! --- Using FontAwesome
  book:
    icon: far fa-address-book
    link: https://live.bilibili.com/22619211

#! ---------------------------------------------------------------
#! Site Meta Configs
#! @docs https://aurora.tridiamond.tech/guide/theme.html
#! ---------------------------------------------------------------

# 网页META
site_meta:
  cdn: cn
  favicon:
  # 对站点的描述
  description: '记录知识，记录成长'
  # 网站的关键词
  keywords: 'HTML,CSS,JavaScript,C++,Java,python,Vue,TypeScript,React, Blog'
  # 网站作者
  author: 'Cxzxy'
# 自定义 Meta, 自定义 Script 或 CSS 链接添加到主题中
# injects:
#   scripts:
#     - <script src="https://cdn.jsdelivr.net/gh/Fan223/live2d-widget@latest/autoload.js"></script>
#   css:
#     - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css">
